name: "Debug APK Publisher"
branding:
  icon: "package"
  color: "red"
description: "Build & Publish Debug pre release APK on Github"
author: "rng74"
inputs:
  GITHUB_TOKEN:
    description: "Github secret token to allow automated publishing of APK to release."
runs:
  using: "docker"
  image: "Dockerfile"
